# This file was generated by GoReleaser. DO NOT EDIT.
cask "lctl" do
  name "lctl"
  desc "CLI for managing launchctl servers, sites, and deployments"
  homepage "https://launchctl.io"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lctl"

  on_macos do
    on_intel do
      url "https://github.com/kkz6/launchctl-cli/releases/download/v#{version}/lctl-darwin-amd64.tar.gz"
      sha256 "18b50163a24f76c4887830b544a743065548e22be3251cc7f23084fdec463a70"
    end
    on_arm do
      url "https://github.com/kkz6/launchctl-cli/releases/download/v#{version}/lctl-darwin-arm64.tar.gz"
      sha256 "36cb49f9d1ae37d3b5cfb4257a87cec6ebf78c34b8fc2e590852ac12f26f8964"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kkz6/launchctl-cli/releases/download/v#{version}/lctl-linux-amd64.tar.gz"
      sha256 "b5a48d51408885d945ad6386e2123838cf31f3b4b21cca1052509707baff7aa3"
    end
    on_arm do
      url "https://github.com/kkz6/launchctl-cli/releases/download/v#{version}/lctl-linux-arm64.tar.gz"
      sha256 "6e23257748161f845d3b670077fd9bb93470beb11fca526340cdf8fee21b17bb"
    end
  end

  # No zap stanza required
end
