# This file was generated by GoReleaser. DO NOT EDIT.
cask "lctl" do
  name "lctl"
  desc "CLI for managing launchctl servers, sites, and deployments"
  homepage "https://launchctl.io"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lctl"

  on_macos do
    on_intel do
      url "https://sin1.contabostorage.com/launchctl-cli/v#{version}/lctl-darwin-amd64.tar.gz"
      sha256 "6f2cbb8a6c0b289419eba3bc5c10b53086896ef6865981a39f91b17c0e5c18ff"
    end
    on_arm do
      url "https://sin1.contabostorage.com/launchctl-cli/v#{version}/lctl-darwin-arm64.tar.gz"
      sha256 "9d25d2f8ca35c6295a2d8687f547de2623eba36529856f290013ee7cc39f8353"
    end
  end

  on_linux do
    on_intel do
      url "https://sin1.contabostorage.com/launchctl-cli/v#{version}/lctl-linux-amd64.tar.gz"
      sha256 "4658068faf3ba51856b605ad1a2eb88480e1cb16cf84f98da6528aed307b17a8"
    end
    on_arm do
      url "https://sin1.contabostorage.com/launchctl-cli/v#{version}/lctl-linux-arm64.tar.gz"
      sha256 "c83a598fdeacee0f4f9b129239db9ec072847a8cf2bf9a9e8007b39c4c9bb0ad"
    end
  end

  # No zap stanza required
end
