# This file was generated by GoReleaser. DO NOT EDIT.
cask "lctl" do
  name "lctl"
  desc "CLI for managing launchctl servers, sites, and deployments"
  homepage "https://launchctl.io"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lctl"

  on_macos do
    on_intel do
      url "https://sin1.contabostorage.com/2fac7399ecc245c4b352abf9eb154e1d:launchctl-cli/v#{version}/lctl-darwin-amd64.tar.gz"
      sha256 "160ab94746e70d56affc6ce1be7f921e4421e6d6d517380279e6971af361422b"
    end
    on_arm do
      url "https://sin1.contabostorage.com/2fac7399ecc245c4b352abf9eb154e1d:launchctl-cli/v#{version}/lctl-darwin-arm64.tar.gz"
      sha256 "897bcd6231e60f0b2396d5c84f13a5bda0ab004ad41a7497b093ebf6c6303d58"
    end
  end

  on_linux do
    on_intel do
      url "https://sin1.contabostorage.com/2fac7399ecc245c4b352abf9eb154e1d:launchctl-cli/v#{version}/lctl-linux-amd64.tar.gz"
      sha256 "cfbd40d23926d06cdaa3de24fc8e478e7339be6f5ef51ef4beca95baeb8e7e54"
    end
    on_arm do
      url "https://sin1.contabostorage.com/2fac7399ecc245c4b352abf9eb154e1d:launchctl-cli/v#{version}/lctl-linux-arm64.tar.gz"
      sha256 "47b47507215cfd065ae319a1d761b7743fcbaa3c5674ce510483349c31bb622b"
    end
  end

  # No zap stanza required
end
